### ISSUE TITLE
Geyma og birta líka dagsetningar en ekki bara tímasetningar

### ISSUE THREAD

**Issue by bjk17** [bjk17/cinema#6]
Betra UX

**Comment by bjk17** [comment]
Gæti líka verið betri lausn á issue #5 til að minnka áreiti á gagnagrunn.

**Comment by kristrunskuladottir** [comment]
If JSON file was requested just before midnight, showtimes would not be updated until 60 minutes later so movies/showtimes from yesterday were shown on the page.

**Comment by kristrunskuladottir** [comment]
We will resolve this by clearing cache if it's from yesterday. We will also show the date of the showtimes on top of the page. ( #22 and #23 ).
